instantTest/urls.py
from django.conf.urls import patterns, include, url



urlpatterns = patterns('instantTest.views',
    # Examples:
    # url(r'^$', 'onlineTest.views.home', name='home'),
    # url(r'^onlineTest/', include('onlineTest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$','signin'),
    url(r'myTest/$','index'),
    url(r'^(?P<test_id>\d+)/(?P<question_id>\d+)/$', 'details'),
    
)

onlineTest/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'onlineTest.views.home', name='home'),
    # url(r'^onlineTest/', include('onlineTest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^instantTest/', include('instantTest.urls')),  
    url(r'^admin/', include(admin.site.urls)),
)

instantTest/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Point(models.Model):
    point = models.CharField(max_length = 200)
    def __unicode__(self):
        return self.point

        
class Question(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    answer = models.IntegerField(default=0)
    point = models.ManyToManyField(Point)
    def __unicode__(self):
        return self.question
    def knowledge_points(self):
        return ', '.join([a.point for a in self.point.all()])
    knowledge_points.short_description = "Knowledge Point"

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice = models.CharField(max_length = 200)
    def __unicode__(self):
       return self.choice

class Paper(models.Model):
    questions = models.ManyToManyField(Question)
    name = models.CharField(max_length = 200)

    def __unicode__(self):
        return self.name

class Test(models.Model):
    paper = models.ForeignKey(Paper)
    grade = models.IntegerField(default = 0)
    student = models.ForeignKey(User)
    def __studentName(self):
        return student.username
    #dueDate =models.DateTimeField('date overdue')
    def __unicode__(self):
        return self.paper.name

instantTest/views.py
# Create your views here.
from django.template import Context,loader, RequestContext
from instantTest.models import Question,Test,Paper
from django.http import HttpResponse, Http404,HttpResponseRedirect
from django.shortcuts import render_to_response , get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.views.decorators.cache import never_cache 
def signin(request):
     return render_to_response('instantTest/signin.html' ,context_instance=RequestContext(request))


def index(request):
	 paperid = request.GET['paperid']
	 username = request.GET['username']
	 password = request.GET['password']
	 user = auth.authenticate(username=username,password=password)
	 
	 if user is not None and user.is_active:
	 	auth.login(request,user)
	 	testPaper = get_object_or_404(Paper,pk=paperid)
	 	if Test.objects.filter(paper=testPaper,student=user):
	 		return render_to_response('instantTest/signin.html' ,{'error_message':"invalid test",},context_instance=RequestContext(request))
	 	test = Test(paper=testPaper,grade=0,student=user)
	 	test.grade = 0
	 	test.save()
	 	# request.session[str(0)]='1'
	 	return render_to_response('instantTest/index.html' ,{'test': test, })
	 else:
	    return render_to_response('instantTest/signin.html' ,{'error_message':"username or password isn't correct."},context_instance=RequestContext(request))
	    


@never_cache
def details(request,test_id,question_id):

	 
	 test = get_object_or_404(Test,pk=test_id)
	 post_question_id = int(question_id)-1

	 # session_qid =int(request.session[question_id])
	 if question_id in request.session:
	 	return render_to_response('instantTest/signin.html',{'error_message':"invalid operation",},context_instance=RequestContext(request))
	 request.session[question_id]='1';
     
         
 
	 if post_question_id>=0:
	 	post_question = test.paper.questions.all()[post_question_id]
	 	if 'choice' in request.POST:
	 		if int(post_question.answer) == int(request.POST['choice']):
	 		     test.grade+=1
	 		     test.save()
	 	
	 if len(test.paper.questions.all())>int(question_id):
	 	question = test.paper.questions.all()[int(question_id)]
	 	qid = int(question_id)+1
	 	
	 	return render_to_response('instantTest/details.html',{'test':test,'question_id':qid,'question':question,},context_instance=RequestContext(request))
        
	 
	 #return HttpResponse("your grade is %s"%test.grade)
	 #log out
	 return render_to_response('instantTest/result.html',{'grade':test.grade},)

	

onlineTest/templates/instantTest/details.html
<head>
<meta http-equiv="Expires" CONTENT="0">  
<meta http-equiv="Cache-Control" CONTENT="no-cache">  
<meta http-equiv="Pragma" CONTENT="no-cache">  
<meta http-equiv = "refresh" content ="5;url=/instantTest/{{test.id}}/{{next_id}}/" >
</head>

{% if question.question %}
   <h1> {{question.question}}</h1>
   <h2> grade is {{test.grade}}</h2>
   <form action="/instantTest/{{test.id}}/{{question_id}}/" method="post">
   {% csrf_token %}

   {% for choice in question.choice_set.all %}

      <input type = "radio" name ="choice" id ="choice{{forloop.counter}}" value="{{forloop.counter}}"/>
      <label for="choice{{forloop.counter}}">{{choice.choice}}</label><br/>
   {% endfor %}
<input type ="submit" value="submit" />
</form>
{% endif %}

onlineTest/templates/instantTest/index.html
{{test.paper.name}}

<a href = "/instantTest/{{test.id}}/0/">Test Begin</a>

onlineTest/templates/instantTest/result.html
<meta http-equiv = "refresh" content ="5;url=/instantTest/" >
your grade is {{grade}}

onlineTest/templates/instantTest/signin.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="/instantTest/myTest" method="get">
{% csrf_token %}
 测试码<input type = "text" name = "paperid" /></br>
 用户名<input type = "text" name = "username"/></br>
 密码<input type = "text" name = "password"/></br>
 <input type ="submit" value="begin test" />
</form>